/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AccountType = { 'seller' : null } |
  { 'buyer' : null } |
  { 'partner' : null } |
  { 'investor' : null };
export interface AdminStats {
  'totalBuyerRequests' : bigint,
  'partnerCount' : bigint,
  'investorCount' : bigint,
  'totalListings' : bigint,
  'totalInvestorProfiles' : bigint,
  'sellerCount' : bigint,
  'totalPartnerOpportunities' : bigint,
  'totalProblems' : bigint,
  'buyerCount' : bigint,
}
export interface BuyerRequest {
  'id' : bigint,
  'title' : string,
  'owner' : Principal,
  'description' : string,
  'category' : string,
  'budget' : bigint,
  'location' : string,
  'contactPhone' : string,
}
export interface InvestorProfile {
  'id' : bigint,
  'minBudget' : bigint,
  'owner' : Principal,
  'description' : string,
  'sector' : string,
  'location' : string,
  'contactPhone' : string,
  'maxBudget' : bigint,
}
export interface Listing {
  'id' : bigint,
  'title' : string,
  'owner' : Principal,
  'description' : string,
  'category' : string,
  'price' : bigint,
  'location' : string,
  'contactPhone' : string,
}
export interface Message {
  'id' : bigint,
  'senderLocation' : string,
  'subject' : string,
  'body' : string,
  'isRead' : boolean,
  'timestamp' : bigint,
  'senderName' : string,
  'senderAccountType' : AccountType,
  'recipientId' : Principal,
  'senderId' : Principal,
}
export interface PartnerOpportunity {
  'id' : bigint,
  'investmentNeeded' : bigint,
  'title' : string,
  'owner' : Principal,
  'businessType' : string,
  'description' : string,
  'location' : string,
  'contactPhone' : string,
}
export interface Problem {
  'id' : bigint,
  'upvotes' : bigint,
  'title' : string,
  'owner' : Principal,
  'description' : string,
  'category' : string,
  'location' : string,
}
export interface UserDirectoryEntry {
  'principal' : Principal,
  'city' : string,
  'name' : string,
  'accountType' : AccountType,
}
export interface UserProfile {
  'city' : string,
  'name' : string,
  'email' : string,
  'accountType' : AccountType,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAdminStats' : ActorMethod<[], AdminStats>,
  'getAllBuyerRequests' : ActorMethod<[], Array<BuyerRequest>>,
  'getAllInvestorProfiles' : ActorMethod<[], Array<InvestorProfile>>,
  'getAllListings' : ActorMethod<[], Array<Listing>>,
  'getAllPartnerOpportunities' : ActorMethod<[], Array<PartnerOpportunity>>,
  'getAllPosts' : ActorMethod<
    [],
    {
      'listings' : Array<Listing>,
      'partnerOpportunities' : Array<PartnerOpportunity>,
      'investorProfiles' : Array<InvestorProfile>,
      'buyerRequests' : Array<BuyerRequest>,
    }
  >,
  'getAllProblems' : ActorMethod<[], Array<Problem>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMyInbox' : ActorMethod<[], Array<Message>>,
  'getMySentMessages' : ActorMethod<[], Array<Message>>,
  'getUserDirectory' : ActorMethod<[], Array<UserDirectoryEntry>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markAsRead' : ActorMethod<[bigint], undefined>,
  'postBuyerRequest' : ActorMethod<
    [string, string, bigint, string, string, string],
    undefined
  >,
  'postInvestorProfile' : ActorMethod<
    [string, bigint, bigint, string, string, string],
    undefined
  >,
  'postListing' : ActorMethod<
    [string, string, bigint, string, string, string],
    undefined
  >,
  'postPartnerOpportunity' : ActorMethod<
    [string, string, string, bigint, string, string],
    undefined
  >,
  'postProblem' : ActorMethod<[string, string, string, string], undefined>,
  'registerUser' : ActorMethod<[UserProfile], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendMessage' : ActorMethod<[Principal, string, string], undefined>,
  'upvoteProblem' : ActorMethod<[bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];