/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface BuyerRequest {
    id: bigint;
    title: string;
    owner: Principal;
    description: string;
    category: string;
    budget: bigint;
    location: string;
    contactPhone: string;
}
export interface UserDirectoryEntry {
    principal: Principal;
    city: string;
    name: string;
    accountType: AccountType;
}
export interface Listing {
    id: bigint;
    title: string;
    owner: Principal;
    description: string;
    category: string;
    price: bigint;
    location: string;
    contactPhone: string;
}
export interface InvestorProfile {
    id: bigint;
    minBudget: bigint;
    owner: Principal;
    description: string;
    sector: string;
    location: string;
    contactPhone: string;
    maxBudget: bigint;
}
export interface AdminStats {
    totalBuyerRequests: bigint;
    partnerCount: bigint;
    investorCount: bigint;
    totalListings: bigint;
    totalInvestorProfiles: bigint;
    sellerCount: bigint;
    totalPartnerOpportunities: bigint;
    totalProblems: bigint;
    buyerCount: bigint;
}
export interface Problem {
    id: bigint;
    upvotes: bigint;
    title: string;
    owner: Principal;
    description: string;
    category: string;
    location: string;
}
export interface Message {
    id: bigint;
    senderLocation: string;
    subject: string;
    body: string;
    isRead: boolean;
    timestamp: bigint;
    senderName: string;
    senderAccountType: AccountType;
    recipientId: Principal;
    senderId: Principal;
}
export interface UserProfile {
    city: string;
    name: string;
    email: string;
    accountType: AccountType;
    phone: string;
}
export interface PartnerOpportunity {
    id: bigint;
    investmentNeeded: bigint;
    title: string;
    owner: Principal;
    businessType: string;
    description: string;
    location: string;
    contactPhone: string;
}
export enum AccountType {
    seller = "seller",
    buyer = "buyer",
    partner = "partner",
    investor = "investor"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    getAdminStats(): Promise<AdminStats>;
    getAllBuyerRequests(): Promise<Array<BuyerRequest>>;
    getAllInvestorProfiles(): Promise<Array<InvestorProfile>>;
    getAllListings(): Promise<Array<Listing>>;
    getAllPartnerOpportunities(): Promise<Array<PartnerOpportunity>>;
    getAllPosts(): Promise<{
        listings: Array<Listing>;
        partnerOpportunities: Array<PartnerOpportunity>;
        investorProfiles: Array<InvestorProfile>;
        buyerRequests: Array<BuyerRequest>;
    }>;
    getAllProblems(): Promise<Array<Problem>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getMyInbox(): Promise<Array<Message>>;
    getMySentMessages(): Promise<Array<Message>>;
    getUserDirectory(): Promise<Array<UserDirectoryEntry>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    markAsRead(messageId: bigint): Promise<void>;
    postBuyerRequest(title: string, description: string, budget: bigint, category: string, location: string, contactPhone: string): Promise<void>;
    postInvestorProfile(sector: string, minBudget: bigint, maxBudget: bigint, location: string, description: string, contactPhone: string): Promise<void>;
    postListing(title: string, description: string, price: bigint, category: string, location: string, contactPhone: string): Promise<void>;
    postPartnerOpportunity(title: string, description: string, businessType: string, investmentNeeded: bigint, location: string, contactPhone: string): Promise<void>;
    postProblem(title: string, description: string, location: string, category: string): Promise<void>;
    registerUser(profile: UserProfile): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    sendMessage(recipientId: Principal, subject: string, body: string): Promise<void>;
    upvoteProblem(id: bigint): Promise<void>;
}
import type { AccountType as _AccountType, Message as _Message, UserDirectoryEntry as _UserDirectoryEntry, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async getAdminStats(): Promise<AdminStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminStats();
            return result;
        }
    }
    async getAllBuyerRequests(): Promise<Array<BuyerRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBuyerRequests();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBuyerRequests();
            return result;
        }
    }
    async getAllInvestorProfiles(): Promise<Array<InvestorProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllInvestorProfiles();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllInvestorProfiles();
            return result;
        }
    }
    async getAllListings(): Promise<Array<Listing>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllListings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllListings();
            return result;
        }
    }
    async getAllPartnerOpportunities(): Promise<Array<PartnerOpportunity>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPartnerOpportunities();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPartnerOpportunities();
            return result;
        }
    }
    async getAllPosts(): Promise<{
        listings: Array<Listing>;
        partnerOpportunities: Array<PartnerOpportunity>;
        investorProfiles: Array<InvestorProfile>;
        buyerRequests: Array<BuyerRequest>;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPosts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPosts();
            return result;
        }
    }
    async getAllProblems(): Promise<Array<Problem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllProblems();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllProblems();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyInbox(): Promise<Array<Message>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyInbox();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyInbox();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMySentMessages(): Promise<Array<Message>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMySentMessages();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMySentMessages();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserDirectory(): Promise<Array<UserDirectoryEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserDirectory();
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserDirectory();
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async markAsRead(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markAsRead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markAsRead(arg0);
            return result;
        }
    }
    async postBuyerRequest(arg0: string, arg1: string, arg2: bigint, arg3: string, arg4: string, arg5: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.postBuyerRequest(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.postBuyerRequest(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async postInvestorProfile(arg0: string, arg1: bigint, arg2: bigint, arg3: string, arg4: string, arg5: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.postInvestorProfile(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.postInvestorProfile(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async postListing(arg0: string, arg1: string, arg2: bigint, arg3: string, arg4: string, arg5: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.postListing(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.postListing(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async postPartnerOpportunity(arg0: string, arg1: string, arg2: string, arg3: bigint, arg4: string, arg5: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.postPartnerOpportunity(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.postPartnerOpportunity(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async postProblem(arg0: string, arg1: string, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.postProblem(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.postProblem(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async registerUser(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerUser(to_candid_UserProfile_n16(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerUser(to_candid_UserProfile_n16(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n16(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n16(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async sendMessage(arg0: Principal, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.sendMessage(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendMessage(arg0, arg1, arg2);
            return result;
        }
    }
    async upvoteProblem(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.upvoteProblem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.upvoteProblem(arg0);
            return result;
        }
    }
}
function from_candid_AccountType_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AccountType): AccountType {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_Message_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Message): Message {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_UserDirectoryEntry_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserDirectoryEntry): UserDirectoryEntry {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n4(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    senderLocation: string;
    subject: string;
    body: string;
    isRead: boolean;
    timestamp: bigint;
    senderName: string;
    senderAccountType: _AccountType;
    recipientId: Principal;
    senderId: Principal;
}): {
    id: bigint;
    senderLocation: string;
    subject: string;
    body: string;
    isRead: boolean;
    timestamp: bigint;
    senderName: string;
    senderAccountType: AccountType;
    recipientId: Principal;
    senderId: Principal;
} {
    return {
        id: value.id,
        senderLocation: value.senderLocation,
        subject: value.subject,
        body: value.body,
        isRead: value.isRead,
        timestamp: value.timestamp,
        senderName: value.senderName,
        senderAccountType: from_candid_AccountType_n6(_uploadFile, _downloadFile, value.senderAccountType),
        recipientId: value.recipientId,
        senderId: value.senderId
    };
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    principal: Principal;
    city: string;
    name: string;
    accountType: _AccountType;
}): {
    principal: Principal;
    city: string;
    name: string;
    accountType: AccountType;
} {
    return {
        principal: value.principal,
        city: value.city,
        name: value.name,
        accountType: from_candid_AccountType_n6(_uploadFile, _downloadFile, value.accountType)
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    city: string;
    name: string;
    email: string;
    accountType: _AccountType;
    phone: string;
}): {
    city: string;
    name: string;
    email: string;
    accountType: AccountType;
    phone: string;
} {
    return {
        city: value.city,
        name: value.name,
        email: value.email,
        accountType: from_candid_AccountType_n6(_uploadFile, _downloadFile, value.accountType),
        phone: value.phone
    };
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    seller: null;
} | {
    buyer: null;
} | {
    partner: null;
} | {
    investor: null;
}): AccountType {
    return "seller" in value ? AccountType.seller : "buyer" in value ? AccountType.buyer : "partner" in value ? AccountType.partner : "investor" in value ? AccountType.investor : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Message>): Array<Message> {
    return value.map((x)=>from_candid_Message_n11(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserDirectoryEntry>): Array<UserDirectoryEntry> {
    return value.map((x)=>from_candid_UserDirectoryEntry_n14(_uploadFile, _downloadFile, x));
}
function to_candid_AccountType_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AccountType): _AccountType {
    return to_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n17(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    city: string;
    name: string;
    email: string;
    accountType: AccountType;
    phone: string;
}): {
    city: string;
    name: string;
    email: string;
    accountType: _AccountType;
    phone: string;
} {
    return {
        city: value.city,
        name: value.name,
        email: value.email,
        accountType: to_candid_AccountType_n18(_uploadFile, _downloadFile, value.accountType),
        phone: value.phone
    };
}
function to_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AccountType): {
    seller: null;
} | {
    buyer: null;
} | {
    partner: null;
} | {
    investor: null;
} {
    return value == AccountType.seller ? {
        seller: null
    } : value == AccountType.buyer ? {
        buyer: null
    } : value == AccountType.partner ? {
        partner: null
    } : value == AccountType.investor ? {
        investor: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
